name: Deploy to EC2

on:
  push:
    branches:
      - main
      - development
      - 'feature/*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List files in the repository
      run: |
        ls -R

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Copy files to EC2 instance (to /home/ubuntu/app)
      run: |
        scp -i private-key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./your-app-directory ubuntu@98.83.113.5:/home/ubuntu/app

    - name: SSH into EC2 instance and restart the app
      run: |
        ssh -i private-key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@98.83.113.5 "cd /home/ubuntu/app && docker-compose down && docker-compose up -d"
