name: Deploy to EC2

on:
  push:
    branches:
      - main
      - development
      - 'feature/*'  # For feature branches

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Specify your AWS region

    - name: Determine the EC2 Instance IP based on branch
      id: ec2-instance-id
      run: |
        if [ "${GITHUB_REF##*/}" == "main" ]; then
          echo "EC2_INSTANCE_IP=98.83.113.5" >> $GITHUB_ENV
        elif [ "${GITHUB_REF##*/}" == "development" ]; then
          echo "EC2_INSTANCE_IP=3.85.74.66" >> $GITHUB_ENV
        elif [[ "${GITHUB_REF##*/}" == feature/* ]]; then
          echo "EC2_INSTANCE_IP=54.146.33.138" >> $GITHUB_ENV
        fi
        echo "EC2 Instance IP: $EC2_INSTANCE_IP"

    - name: Create SSH key file from secret
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > private-key.pem
        chmod 600 private-key.pem
        echo "Private key created and permissions set"

    - name: Build the app directory (if needed)
      run: |
        # Example build command (if you need to build your app)
        # Replace with your actual build steps
        mkdir -p ./your-app-directory
        echo "This is a test application" > ./your-app-directory/index.html

    - name: Copy files to EC2 instance
      run: |
        scp -i private-key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./your-app-directory ubuntu@${{ env.EC2_INSTANCE_IP }}:/path/to/deployment/directory

    - name: SSH into EC2 instance and restart the app
      run: |
        ssh -i private-key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ env.EC2_INSTANCE_IP }} "cd /path/to/deployment/directory && docker-compose down && docker-compose up -d"
