name: Deploy to EC2

on:
  push:
    branches:
      - main
      - development
      - 'feature/*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Write private key to file
      run: |
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private-key.pem
        chmod 600 private-key.pem  # Ensure the private key has the correct permissions

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Create target directory on EC2 (if not exists)
      run: |
        set -e  # Fail the job if any command fails
        ssh -i private-key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=60 ubuntu@98.83.113.5 "mkdir -p /home/ubuntu/app"


    - name: Copy files to EC2 instance (to /home/ubuntu/app)
      run: |
        scp -i private-key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./your-app-directory/* ubuntu@98.83.113.5:/home/ubuntu/app

    - name: SSH into EC2 instance and restart the app
      run: |
        ssh -i private-key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=30 ubuntu@98.83.113.5 << 'EOF'
          cd /home/ubuntu/app
          docker-compose down
          docker-compose up -d
        EOF
